### ISSUE TITLE
[Feat] 게더링 누락된 부분 수정 및 연동

### ISSUE THREAD

**Issue by joarthvr** [prgrms-web-devcourse-final-project/WEB1_1_ZeroOne_FE#103]
## 📌 작업 내용

- [ ] 게더링 디테일 옵션 contactUrl 사항 표기 
- [ ] 게더링 헤더 글 쓴 유저로 변경
- [ ] 텍스트 에디터 수정
- [ ] 게더링 카드 디자인 수정
- [ ] 게더링 카드 태그 수정

<br/>

## ✅ To-Do

- [ ]
- [ ]

<br/>
