### ISSUE TITLE
[Fix] 프로필 폼 직무 리스트 및 기타 버그 수정

### ISSUE THREAD

**Issue by csk6314** [prgrms-web-devcourse-final-project/WEB1_1_ZeroOne_FE#117]
## 📌 작업 내용
프로필 폼 직무 리스트 불러오기 이슈 및 기타 버그 수정

<br/>

## ✅ To-Do

- [x] 프로필 폼 직무 리스트 이슈 수정
- [x] 모달 스크롤 버그 수정
- [x] 포트폴리오 리스트 사이드 바 위치 버그 수정
- [x] sweetalert 패딩 이슈 수정

<br/>
