### ISSUE TITLE
[Feat] 아카이브 작성 위젯 완성

### ISSUE THREAD

**Issue by he2e2** [prgrms-web-devcourse-final-project/WEB1_1_ZeroOne_FE#32]
## 📌 작업 내용

에디터를 넣고 선택한 컬러를 반영한 아카이브 작성 위젯을 완성합니다. 

<br/>

## ✅ To-Do

- [x] 컬러 선택 -> 작성 위젯에 반영
- [x] 제목 입력 및 태그 입력 컴포넌트 제작
- [x] 댓글 허용 스위치
- [x] 등록

![image](https://github.com/user-attachments/assets/1bb4aefd-5817-45a9-85b3-cb12cf906f07)
