### ISSUE TITLE
[Feat] GatheringSelect Widget 구현

### ISSUE THREAD

**Issue by joarthvr** [prgrms-web-devcourse-final-project/WEB1_1_ZeroOne_FE#35]
## 📌 작업 내용

게더링 페이지 상단 셀렉트 위젯 
![Image](https://github.com/user-attachments/assets/f06d8194-b889-4d70-81aa-948505a5363e)

<br/>

## ✅ To-Do

- [x] 셀렉트 옵션 설정
- [x] 위젯 구성 및 페이지 연동
- [x] 전체 페이지 레이아웃

<br/>
