### ISSUE TITLE
[Feat] sidebar filter 구현 (shared)

### ISSUE THREAD

**Issue by joarthvr** [prgrms-web-devcourse-final-project/WEB1_1_ZeroOne_FE#39]
## 📌 작업 내용

1. 게더링 리스트 페이지의 사이드 메뉴 구현
<br/>

## ✅ To-Do

- [ ] api 연동도 고려하여 구현
- [ ] 기획 내용과 일치하는지 확인
- [ ] 페이지 내에서 레이아웃에 맞게 수정

<br/>

## 📝 참고 사항

![Image](https://github.com/user-attachments/assets/8df71d34-579a-4d0f-adc7-a878eefe5a41)
