### ISSUE TITLE
[Etc] Husky, lint-staged 환경 세팅

### ISSUE THREAD

**Issue by csk6314** [prgrms-web-devcourse-final-project/WEB1_1_ZeroOne_FE#4]
## 📌 작업 내용
- Husky 및 lint-staged 환경 세팅

<br/>

## ✅ To-Do
- [x] husky, lint-staged 패키지 설치
- [x] husky 초기화 및 commit 훅 추가
- [x] lint-staged 설정

<br/>
