### ISSUE TITLE
[Feat] 아카이브 상세 페이지 및 댓글 API 연결

### ISSUE THREAD

**Issue by he2e2** [prgrms-web-devcourse-final-project/WEB1_1_ZeroOne_FE#43]
## 📌 작업 내용

아카이브 상세 페이지 및 댓글 API 작성 후 MSW 핸들러에 연결해 Test 할 예정입니다. 

<br/>

## ✅ To-Do

- [x] 단건 조회 API
- [x] 아카이브 수정
- [x] 아카이브 삭제
- [x] 댓글 리스트 조회
- [x] 댓글 생성
- [x] 댓글 수정 -> 추후 기능
- [x] 댓글 삭제
- [x] MSW 핸들러
