### ISSUE TITLE
[Feat] 마이 페이지 퍼블리싱

### ISSUE THREAD

**Issue by csk6314** [prgrms-web-devcourse-final-project/WEB1_1_ZeroOne_FE#59]
## 📌 작업 내용

마이 페이지 퍼블리싱 작업
<br/>

## ✅ To-Do
- [ ] 페이지 전체 레이아웃 구현
- [ ] 유저 프로필 ui 구현
- [ ] 게더링 탭 컨텐츠 구현
- [ ] 아카이브 탭 컨텐츠 구현 

<br/>
